# Generated by Django 4.2.4 on 2023-11-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_driver_drivinglicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicense',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='main_app.driver'),
        ),
    ]
