# Generated by Django 4.2.4 on 2023-10-24 12:02

from django.db import migrations


def age_group(apps, schema_editor):
    Person = apps.get_model('main_app', 'Person')
    all_records = Person.objects.all()

    for record in all_records:
        if record.age <= 12:
            record.age_group = 'Child'
        elif record.age <= 17:
            record.age_group = 'Teen'
        else:
            record.age_group = 'Adult'

    Person.objects.bulk_create(all_records, ['age_group'])


def revert_age_group(apps, schema_editor):
    Person = apps.get_model('main_app', 'Person')
    all_records = Person.objects.all()

    for record in all_records:
        record.age_group = 'No age group'

    Person.objects.bulk_create(all_records, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(age_group, reverse_code=revert_age_group)
    ]
