# Generated by Django 4.2.4 on 2023-10-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
        ('main_app', '0005_auto_20231024_1022'),
    ]

    operations = [
    ]
