# Generated by Django 4.2.4 on 2023-11-11 20:36

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hero_flashhero_spiderhero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
